### ISSUE TITLE
Please explain plugin usefulness

### ISSUE THREAD

**Issue by pcav** [mkondratyev85/raster_tracer#3]
The functionality described in the About seems already present, at least in part, in other QGIS plugins.
Please clarify what your plugin is actually adding to the current situation.
Sorry for bothering, but we are trying hard not to duplicate functionality, so to reduce confusion for the users and administrative burden.
Thanks.

**Comment by mkondratyev85** [comment]
This plugin digitizes lines in underlying raster map in semi-automatic way. It is useful, for example, when you need to digitize a scanned topographic map, with curved black lines representing lines of equal heights of the surface. Instead of creating this curved vector line by manually clicking at each segment of this curved line to create multi-line, with this plugin you can click at the beginning of the curved line and at the end of the curved line, and it will automatically trace over black pixels (or pixels that are almost black) from the beginning to the end. By using this plugin you reduce clicks while digitizing raster maps. This process is show here: https://github.com/mkondratyev85/raster_tracer/blob/master/screen.gif

The closest plugin to this one is this: https://github.com/its4land/qgis-boundary-delineation. But this plugin is mostly for digitizing remote-sens images, not scanned maps. Please, correct me if I'm wrong.

**Comment by pcav** [comment]
Thanks a lot for the clarification. It would be good if you could add it to the README or the About.
